[trunk] -> [community] 'squid-openrc-20220313-1' add

diff --git a/trunk/squid.initd b/trunk/squid.initd
--- a/trunk/squid.initd
+++ b/trunk/squid.initd
@@ -1,8 +1,18 @@
 #!/usr/bin/openrc-run
 # Copyright 1999-2019 Gentoo Authors
 # Distributed under the terms of the GNU General Public License v2
+# supervised, nous 2022
 
 SQUID_SVCNAME=$( echo "${RC_SVCNAME}" | tr -cd '[a-zA-Z0-9]' )
+SQUID_CONF=/etc/squid/${RC_SVCNAME}.conf
+SQUID_USER=proxy
+SQUID_GROUP=proxy
+
+supervisor=supervise-daemon
+supervise_daemon_args="--respawn-delay 5 --respawn-max 10"
+#pidfile="/run/${SQUID_SVCNAME}-supervise.pid"
+command="/usr/bin/$SQUID_SVCNAME"
+command_args="${SQUID_OPTS} -f $SQUID_CONF -N"
 
 extra_started_commands="reload rotate"
 
@@ -11,9 +21,9 @@ depend() {
 }
 
 checkconfig() {
-	local CONFFILES="/etc/squid/${RC_SVCNAME}.conf /etc/squid/${RC_SVCNAME}.include /etc/squid/${RC_SVCNAME}.include.*"
-	if [ ! -f /etc/squid/${RC_SVCNAME}.conf ]; then
-		eerror "You need to create /etc/squid/${RC_SVCNAME}.conf first."
+	local CONFFILES="$SQUID_CONF /etc/squid/${RC_SVCNAME}.include /etc/squid/${RC_SVCNAME}.include.*"
+	if [ ! -f $SQUID_CONF ]; then
+		eerror "You need to create $SQUID_CONF first."
 		eerror "The main configuration file and all included file names should have the following format:"
 		eerror "${CONFFILES}"
 		eerror "An example can be found in /etc/squid/squid.conf.default"
@@ -23,7 +33,7 @@ checkconfig() {
 	local PIDFILE=$(cat ${CONFFILES} 2>/dev/null 3>/dev/null | awk '/^[ \t]*pid_filename[ \t]+/ { print $2 }')
 	[ -z ${PIDFILE} ] && PIDFILE=/run/squid.pid
 	if [ /run/${RC_SVCNAME}.pid != ${PIDFILE} ]; then
-		eerror "/etc/squid/${RC_SVCNAME}.conf must set pid_filename to"
+		eerror "$SQUID_CONF must set pid_filename to"
 		eerror "   /run/${RC_SVCNAME}.pid"
 		eerror "CAUTION: http_port, cache_dir and *_log parameters must be different than"
 		eerror "         in any other instance of squid."
@@ -51,12 +61,12 @@ checkconfig() {
 			local ORIG_UMASK=$(umask)
 			umask 027
 
-			if ! (mkdir -p ${x%/*} && chown squid ${x%/*}) ; then
+			if ! (mkdir -p ${x%/*} && chown $SQUID_USER:$SQUID_GROUP ${x%/*}) ; then
 				eend 1
 				return 1
 			fi
 
-			local INIT_CACHE_RESPONSE="$(/usr/bin/squid -z -N -f /etc/squid/${RC_SVCNAME}.conf -n ${SQUID_SVCNAME} 2>&1)"
+			local INIT_CACHE_RESPONSE="$($command -z -N -f $SQUID_CONF 2>&1)"
 			if [ $? != 0 ] || echo "$INIT_CACHE_RESPONSE" | grep -q "erminated abnormally" ; then
 				umask $ORIG_UMASK
 				eend 1
@@ -73,53 +83,53 @@ checkconfig() {
 	return 0
 }
 
-start() {
+start_pre() {
 	checkconfig || return 1
-	checkpath -d -q -m 0750 -o squid:squid /run/${RC_SVCNAME}
+	checkpath -d -q -m 0750 -o $SQUID_USER:$SQUID_GROUP /run/${RC_SVCNAME}
 
 	# see https://wiki.squid-cache.org/MultipleInstances
-	ebegin "Starting ${RC_SVCNAME} (service name ${SQUID_SVCNAME}) with KRB5_KTNAME=\"${SQUID_KEYTAB}\" /usr/bin/squid ${SQUID_OPTS} -f /etc/squid/${RC_SVCNAME}.conf -n ${SQUID_SVCNAME}"
-	KRB5_KTNAME="${SQUID_KEYTAB}" /usr/bin/squid ${SQUID_OPTS} -f /etc/squid/${RC_SVCNAME}.conf -n ${SQUID_SVCNAME}
-	eend $? && sleep 1
+	ebegin "Starting ${RC_SVCNAME} (service name ${SQUID_SVCNAME}) with KRB5_KTNAME=\"${SQUID_KEYTAB}\" $command ${SQUID_OPTS} -f $SQUID_CONF"
+#	KRB5_KTNAME="${SQUID_KEYTAB}" $command ${SQUID_OPTS} -f $SQUID_CONF
+#	eend $? && sleep 1
 }
 
-stop() {
-	ebegin "Stopping ${RC_SVCNAME} with /usr/bin/squid -k shutdown -f /etc/squid/${RC_SVCNAME}.conf -n ${SQUID_SVCNAME}"
-	if /usr/bin/squid -k shutdown -f /etc/squid/${RC_SVCNAME}.conf -n ${SQUID_SVCNAME} ; then
-		# Now we have to wait until squid has _really_ stopped.
-		sleep 1
-		if [ -f /run/${RC_SVCNAME}.pid ] ; then
-			einfon "Waiting for squid to shutdown ."
-			cnt=0
-			while [ -f /run/${RC_SVCNAME}.pid ] ; do
-				cnt=$(expr $cnt + 1)
-				if [ $cnt -gt 60 ] ; then
-					# Waited 120 seconds now. Fail.
-					echo
-					eend 1 "Failed."
-					break
-				fi
-				sleep 2
-				printf "."
-			done
-			echo
-		fi
-	else
-		eerror "Squid shutdown failed, probably service is already down."
+stop_pre() {
+	ebegin "Stopping ${RC_SVCNAME} with $command -k shutdown -f $SQUID_CONF $SQUID_OPTS"
+	$command -k shutdown -f $SQUID_CONF $SQUID_OPTS &
+}
+stop_post() {
+	# Now we have to wait until squid has _really_ stopped.
+	sleep 1
+	if [ -f /run/${RC_SVCNAME}.pid ] ; then
+		einfon "Waiting for squid to shutdown ."
+		cnt=0
+		while [ -f /run/${RC_SVCNAME}.pid ]; do
+			cnt=$(expr $cnt + 1)
+			if [ $cnt -gt 60 ] ; then
+				# Waited 120 seconds now. Fail.
+				echo
+				eend 1 "Failed."
+				break
+			fi
+			sleep 2
+			printf "."
+		done
+		echo
 	fi
+	[ -f /run/${RC_SVCNAME}.pid ] && eerror "Squid shutdown failed, probably service is already down."
 	eend 0
 }
 
 reload() {
 	checkconfig || return 1
-	ebegin "Reloading ${RC_SVCNAME} with /usr/bin/squid -k reconfigure -f /etc/squid/${RC_SVCNAME}.conf -n ${SQUID_SVCNAME}"
-	/usr/bin/squid -k reconfigure -f /etc/squid/${RC_SVCNAME}.conf -n ${SQUID_SVCNAME}
+	ebegin "Reloading ${RC_SVCNAME} with $command -k reconfigure -f $SQUID_CONF"
+	$command -k reconfigure -f $SQUID_CONF -n ${SQUID_SVCNAME}
 	eend $?
 }
 
 rotate() {
 	service_started ${RC_SVCNAME} || return 1
-	ebegin "Rotating ${RC_SVCNAME} logs with /usr/bin/squid -k rotate -f /etc/squid/${RC_SVCNAME}.conf -n ${SQUID_SVCNAME}"
-	/usr/bin/squid -k rotate -f /etc/squid/${RC_SVCNAME}.conf -n ${SQUID_SVCNAME}
+	ebegin "Rotating ${RC_SVCNAME} logs with $command -k rotate -f $SQUID_CONF"
+	$command -k rotate -f $SQUID_CONF -n ${SQUID_SVCNAME}
 	eend $?
 }
