[testing] -> [core] 's6-rc-0.5.1.2-7' move

diff --git a/x86_64/core/s6-rc-bundle-update b/x86_64/core/s6-rc-bundle-update
--- a/x86_64/core/s6-rc-bundle-update
+++ b/x86_64/core/s6-rc-bundle-update
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/sh
 
 BUNDLENAME=""
 c_arg=false
@@ -7,20 +7,20 @@ CONTENTS=""
 DATABASE="/run/s6-rc/compiled"
 HELP_MSG="s6-rc-bundle-update: usage: s6-rc-bundle-update [ -c compiled ] command... (use s6-rc-bundle-update help for more information)"
 for arg in "$@"; do
-	if [[ "$c_arg" = true ]]; then
+	if [ "$c_arg" = true ]; then
 		DATABASE=$arg
 		c_arg=false
 		continue
 	fi
-	if [[ $arg = "-c" ]]; then
+	if [ "$arg" = "-c" ]; then
 		c_arg=true
 		continue
 	fi
-	if [[ $COMMAND = "" ]]; then
+	if [ "$COMMAND" = "" ]; then
 		COMMAND=$arg
 		continue
 	fi
-	if [[ $BUNDLENAME = "" ]]; then
+	if [ "$BUNDLENAME" = "" ]; then
 		BUNDLENAME=$arg
 		continue
 	fi
@@ -40,26 +40,22 @@ case $COMMAND in
 		exit 1
 	fi
 	isbundle=$(s6-rc-db -c $DATABASE type "$BUNDLENAME" 2> /dev/null)
-	if [[ "$?" == 111 ]]; then
+	if [ "$?" == 111 ]; then
 		echo "s6-rc-bundle-update: fatal: unable to take lock on $DATABASE: Permission denied"
 		exit 1
 	fi
-	if [[ "$isbundle" != "bundle" ]]; then
+	if [ "$isbundle" != "bundle" ]; then
 		echo "$BUNDLENAME is not an existing bundle. Create it with s6-rc-bundle."
 		exit 1
 	fi
 
-	echo "$(s6-rc-db -c $DATABASE contents $BUNDLENAME)" > /etc/s6/$BUNDLENAME.backup
+	old=$(s6-rc-db -c $DATABASE contents $BUNDLENAME)
 	s6-rc-bundle -c $DATABASE delete $BUNDLENAME
-	old=$(echo $(cat /etc/s6/$BUNDLENAME.backup))
-	if [[ -n $old ]]; then
-		ret=$(s6-rc-bundle -c $DATABASE add $BUNDLENAME $old $CONTENTS)
-		if [[ "$?" != 0 ]]; then
-			echo "Error when trying to add $CONTENTS!"
-			s6-rc-bundle -c $DATABASE add $BUNDLENAME $old
-		fi
-	fi
-	rm /etc/s6/$BUNDLENAME.backup;;
+	ret=$(s6-rc-bundle -c $DATABASE add $BUNDLENAME $old $CONTENTS)
+	if [ "$?" != 0 ]; then
+		echo "Error when trying to add$CONTENTS!"
+		s6-rc-bundle -c $DATABASE add $BUNDLENAME $old
+	fi;;
     
     delete)
 	if [ "$#" -lt 3 ]; then
@@ -67,30 +63,40 @@ case $COMMAND in
 		exit 1
 	fi
 	isbundle=$(s6-rc-db -c $DATABASE type "$BUNDLENAME" 2> /dev/null)
-	if [[ "$?" == 111 ]]; then
+	if [ "$?" == 111 ]; then
 		echo "s6-rc-bundle-update: fatal: unable to take lock on $DATABASE: Permission denied"
 		exit 1
 	fi
-	if [[ "$isbundle" != "bundle" ]]; then
+	if [ "$isbundle" != "bundle" ]; then
 		echo "$BUNDLENAME is not an existing bundle. Create it with s6-rc-bundle"
 		exit 1
 	fi
-	echo "$(s6-rc-db -c $DATABASE contents $BUNDLENAME)" > /etc/s6/$BUNDLENAME.backup
-	s6-rc-bundle -c $DATABASE delete $BUNDLENAME
-	old=$(echo $(cat /etc/s6/$BUNDLENAME.backup))
+	old=$(s6-rc-db -c $DATABASE contents $BUNDLENAME)
 	for entry in $CONTENTS; do
-		ret=$(grep -x $entry /etc/s6/$BUNDLENAME.backup)
-		if [[ "$?" != 0 ]]; then
-			echo "$entry does not exist in bundle $BUNDLENAME!"
-			s6-rc-bundle -c $DATABASE add $BUNDLENAME $old
-			rm /etc/s6/$BUNDLENAME.backup
-			exit 1
+		isbundle=$(s6-rc-db -c $DATABASE type "$entry" 2> /dev/null)
+		if [ "$isbundle" == "bundle" ]; then
+			entrycontents=$(s6-rc-db -c $DATABASE contents $entry)
 		else
-			sed -i "/$entry/d" /etc/s6/$BUNDLENAME.backup
+			entrycontents=$entry
 		fi
+		for srv in $entrycontents; do
+			ret=$(echo $old | grep -w $srv)
+			if [ "$?" != 0 ]; then
+				echo "$entry does not exist in bundle $BUNDLENAME!"
+				exit 1
+			else
+				oldupdated=""
+				for oldsrv in $old; do
+					if [ "$oldsrv" != "$srv" ]; then
+						oldupdated="${oldupdated} $oldsrv"
+					fi
+				done
+				old=$oldupdated
+			fi
+		done
 	done
-	s6-rc-bundle -c $DATABASE add $BUNDLENAME $(echo $(cat /etc/s6/$BUNDLENAME.backup))
-	rm /etc/s6/$BUNDLENAME.backup;;
+	s6-rc-bundle -c $DATABASE delete $BUNDLENAME
+	s6-rc-bundle -c $DATABASE add $BUNDLENAME $old;;
     
     list)
 	if [ "$#" -lt 2 ]; then
@@ -98,11 +104,11 @@ case $COMMAND in
 		exit 1
 	fi
 	isbundle=$(s6-rc-db -c $DATABASE type "$BUNDLENAME" 2> /dev/null)
-	if [[ "$?" == 111 ]]; then
+	if [ "$?" == 111 ]; then
 		echo "s6-rc-bundle-update: fatal: unable to take lock on $DATABASE: Permission denied"
 		exit 1
 	fi
-	if [[ "$isbundle" != "bundle" ]]; then
+	if [ "$isbundle" != "bundle" ]; then
 		echo "$BUNDLENAME is not an existing bundle. Create it with s6-rc-bundle"
 		exit 1
 	fi
